            <div class="listPaginador">
            
               <ul class="paginadorOptions">
                  <li>
                      <span>Seleccionados:</span>
                  </li>
                  <li>
                      <a href="#" class="print"><img src="/images/icons/printer.png" title="Imprimir pagina"/> Imprimir</a> 
                  </li>
                  <li>
                      <a href="#" class="delete"><img src="/images/icons/page_delete.png" title="Eliminar elementos seleccionados"/> Eliminar</a>
                  </li>
               </ul> <!-- /paginadorOptions -->
                
               <div class="paginadorCant">
                  <p>Mostrar 
                     <a href="/{$varController}/{$varAction}/{if $Pagado}Pagado/{$Pagado}/{/if}{if $Pendientes}Pendientes/{$Pendientes}/{/if}{if $ProveedorId}ProveedorId/{$ProveedorId}/{/if}{if $Nombre}Nombre/{$Nombre}/{/if}{if $EstadoSeleccionado}Estado/{$EstadoSeleccionado}/{/if}{if $FechaDesde}FechaDesde/{$FechaDesde}/{/if}{if $FechaHasta}FechaHasta/{$FechaHasta}/{/if}{if $EstadoId >= 0 and $EstadoId}EstadoOrdenTrabajoId/{$EstadoId}/{/if}{if $NombreProveedor}NombreProveedor/{$NombreProveedor}/{/if}{if $OrdenDeCompraId}OrdenDeCompraId/{$OrdenDeCompraId}/{/if}{if $OrdenDePagoId}OrdenDePagoId/{$OrdenDePagoId}/{/if}{if $OrdenEstadoId >= 0 and $OrdenEstadoId }EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $NombreCliente}NombreCliente/{$NombreCliente}/{/if}{if $ProveedorNombre}ProveedorNombre/{$ProveedorNombre}/{/if}{if $FacturaId}FacturaId/{$FacturaId}/{/if}{if $FacturaTipo}FacturaTipo/{$FacturaTipo}/{/if}{if $OrdenDeTrabajoId}OrdenDeTrabajoId/{$OrdenDeTrabajoId}/{/if}{if $OrdenEstadoId >= 0}EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $SelectedPrioridadId}PrioridadId/{$SelectedPrioridadId}/{/if}pagesize/15/page/{$list.page}{if $orderBy}/order/{$orderBy}_{$order}{/if}{if $search}/search/{$search}{/if}" {if $list.pageSize eq 15}class="active"{/if}>15</a> | 
                     <a href="/{$varController}/{$varAction}/{if $Pagado}Pagado/{$Pagado}/{/if}{if $Pendientes}Pendientes/{$Pendientes}/{/if}{if $ProveedorId}ProveedorId/{$ProveedorId}/{/if}{if $Nombre}Nombre/{$Nombre}/{/if}{if $EstadoSeleccionado}Estado/{$EstadoSeleccionado}/{/if}{if $FechaDesde}FechaDesde/{$FechaDesde}/{/if}{if $FechaHasta}FechaHasta/{$FechaHasta}/{/if}{if $EstadoId >= 0 and $EstadoId}EstadoOrdenTrabajoId/{$EstadoId}/{/if}{if $NombreProveedor}NombreProveedor/{$NombreProveedor}/{/if}{if $OrdenDeCompraId}OrdenDeCompraId/{$OrdenDeCompraId}/{/if}{if $OrdenDePagoId}OrdenDePagoId/{$OrdenDePagoId}/{/if}{if $OrdenEstadoId >= 0 and $OrdenEstadoId }EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $NombreCliente}NombreCliente/{$NombreCliente}/{/if}{if $ProveedorNombre}ProveedorNombre/{$ProveedorNombre}/{/if}{if $FacturaId}FacturaId/{$FacturaId}/{/if}{if $FacturaTipo}FacturaTipo/{$FacturaTipo}/{/if}{if $OrdenDeTrabajoId}OrdenDeTrabajoId/{$OrdenDeTrabajoId}/{/if}{if $OrdenEstadoId >= 0}EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $SelectedPrioridadId}PrioridadId/{$SelectedPrioridadId}/{/if}pagesize/50/page/{$list.page}{if $orderBy}/order/{$orderBy}_{$order}{/if}{if $search}/search/{$search}{/if}" {if $list.pageSize eq 50}class="active"{/if}>50</a> | 
                     <a href="/{$varController}/{$varAction}/{if $Pagado}Pagado/{$Pagado}/{/if}{if $Pendientes}Pendientes/{$Pendientes}/{/if}{if $ProveedorId}ProveedorId/{$ProveedorId}/{/if}{if $Nombre}Nombre/{$Nombre}/{/if}{if $EstadoSeleccionado}Estado/{$EstadoSeleccionado}/{/if}{if $FechaDesde}FechaDesde/{$FechaDesde}/{/if}{if $FechaHasta}FechaHasta/{$FechaHasta}/{/if}{if $EstadoId >= 0 and $EstadoId}EstadoOrdenTrabajoId/{$EstadoId}/{/if}{if $NombreProveedor}NombreProveedor/{$NombreProveedor}/{/if}{if $OrdenDeCompraId}OrdenDeCompraId/{$OrdenDeCompraId}/{/if}{if $OrdenDePagoId}OrdenDePagoId/{$OrdenDePagoId}/{/if}{if $OrdenEstadoId >= 0 and $OrdenEstadoId }EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $NombreCliente}NombreCliente/{$NombreCliente}/{/if}{if $ProveedorNombre}ProveedorNombre/{$ProveedorNombre}/{/if}{if $FacturaId}FacturaId/{$FacturaId}/{/if}{if $FacturaTipo}FacturaTipo/{$FacturaTipo}/{/if}{if $OrdenDeTrabajoId}OrdenDeTrabajoId/{$OrdenDeTrabajoId}/{/if}{if $OrdenEstadoId >= 0}EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $SelectedPrioridadId}PrioridadId/{$SelectedPrioridadId}/{/if}pagesize/100/page/{$list.page}{if $orderBy}/order/{$orderBy}_{$order}{/if}{if $search}/search/{$search}{/if}" {if $list.pageSize eq 100}class="active"{/if}>100</a>
                  </p>
               </div> <!-- /paginadorCant -->
                
               <div class="paginadorGoTo">
                  <input type="text" class="goTo" value="Ir a pag." />
                  <input type="hidden" class="goToPage" value="/{$varController}/{$varAction}/{if $Pagado}Pagado/{$Pagado}/{/if}{if $Pendientes}Pendientes/{$Pendientes}/{/if}{if $ProveedorId}ProveedorId/{$ProveedorId}/{/if}{if $Nombre}Nombre/{$Nombre}/{/if}{if $EstadoSeleccionado}Estado/{$EstadoSeleccionado}/{/if}{if $FechaDesde}FechaDesde/{$FechaDesde}/{/if}{if $FechaHasta}FechaHasta/{$FechaHasta}/{/if}{if $EstadoId >= 0 and $EstadoId}EstadoOrdenTrabajoId/{$EstadoId}/{/if}{if $NombreProveedor}NombreProveedor/{$NombreProveedor}/{/if}{if $OrdenDeCompraId}OrdenDeCompraId/{$OrdenDeCompraId}/{/if}{if $OrdenEstadoId >= 0 and $OrdenEstadoId }EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $NombreCliente}NombreCliente/{$NombreCliente}/{/if}{if $ProveedorNombre}ProveedorNombre/{$ProveedorNombre}/{/if}{if $FacturaId}FacturaId/{$FacturaId}/{/if}{if $FacturaTipo}FacturaTipo/{$FacturaTipo}/{/if}{if $OrdenDeTrabajoId}OrdenDeTrabajoId/{$OrdenDeTrabajoId}/{/if}{if $OrdenEstadoId >= 0}EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $SelectedPrioridadId}PrioridadId/{$SelectedPrioridadId}/{/if}pagesize/{$list.pageSize}/page/GOTO{if $orderBy}/order/{$orderBy}_{$order}{/if}{if $search}/search/{$search}{/if}" />
                  <input type="button" class="btText" id="goToPage" value="Ir &raquo;" title="Ir &raquo;" />
               </div> <!-- /paginadorCant -->
               
               <ul class="paginadorPages">
                  <li>
                     <a href="/{$varController}/{$varAction}/{if $Pagado}Pagado/{$Pagado}/{/if}{if $Pendientes}Pendientes/{$Pendientes}/{/if}{if $ProveedorId}ProveedorId/{$ProveedorId}/{/if}{if $Nombre}Nombre/{$Nombre}/{/if}{if $EstadoSeleccionado}Estado/{$EstadoSeleccionado}/{/if}{if $FechaDesde}FechaDesde/{$FechaDesde}/{/if}{if $FechaHasta}FechaHasta/{$FechaHasta}/{/if}{if $EstadoId >= 0 and $EstadoId}EstadoOrdenTrabajoId/{$EstadoId}/{/if}{if $NombreProveedor}NombreProveedor/{$NombreProveedor}/{/if}{if $OrdenDeCompraId}OrdenDeCompraId/{$OrdenDeCompraId}/{/if}{if $OrdenEstadoId >= 0 and $OrdenEstadoId }EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $NombreCliente}NombreCliente/{$NombreCliente}/{/if}{if $ProveedorNombre}ProveedorNombre/{$ProveedorNombre}/{/if}{if $FacturaId}FacturaId/{$FacturaId}/{/if}{if $FacturaTipo}FacturaTipo/{$FacturaTipo}/{/if}{if $OrdenDeTrabajoId}OrdenDeTrabajoId/{$OrdenDeTrabajoId}/{/if}{if $OrdenEstadoId >= 0}EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $SelectedPrioridadId}PrioridadId/{$SelectedPrioridadId}/{/if}pagesize/{$list.pageSize}/page/1{if $orderBy}/order/{$orderBy}_{$order}{/if}{if $search}/search/{$search}{/if}" title="Primera">&laquo; Primera</a>
                  </li>
                  <li>
                     <a href="/{$varController}/{$varAction}/{if $Pagado}Pagado/{$Pagado}/{/if}{if $Pendientes}Pendientes/{$Pendientes}/{/if}{if $ProveedorId}ProveedorId/{$ProveedorId}/{/if}{if $Nombre}Nombre/{$Nombre}/{/if}{if $EstadoSeleccionado}Estado/{$EstadoSeleccionado}/{/if}{if $FechaDesde}FechaDesde/{$FechaDesde}/{/if}{if $FechaHasta}FechaHasta/{$FechaHasta}/{/if}{if $EstadoId >= 0  and $EstadoId}EstadoOrdenTrabajoId/{$EstadoId}/{/if}{if $NombreProveedor}NombreProveedor/{$NombreProveedor}/{/if}{if $OrdenDeCompraId}OrdenDeCompraId/{$OrdenDeCompraId}/{/if}{if $OrdenEstadoId >= 0 and $OrdenEstadoId }EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $NombreCliente}NombreCliente/{$NombreCliente}/{/if}{if $ProveedorNombre}ProveedorNombre/{$ProveedorNombre}/{/if}{if $FacturaId}FacturaId/{$FacturaId}/{/if}{if $FacturaTipo}FacturaTipo/{$FacturaTipo}/{/if}{if $OrdenDeTrabajoId}OrdenDeTrabajoId/{$OrdenDeTrabajoId}/{/if}{if $OrdenEstadoId >= 0}EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $SelectedPrioridadId}PrioridadId/{$SelectedPrioridadId}/{/if}pagesize/{$list.pageSize}/page/{if $list.previousPage > 0}{$list.previousPage}{else}1{/if}{if $orderBy}/order/{$orderBy}_{$order}{/if}{if $search}/search/{$search}{/if}" title="Anterior">Anterior</a>
                  </li>
                  <li>
                     {foreach from=$list.range item="pageNum"}
                        <a href="/{$varController}/{$varAction}/{if $Pagado}Pagado/{$Pagado}/{/if}{if $Pendientes}Pendientes/{$Pendientes}/{/if}{if $ProveedorId}ProveedorId/{$ProveedorId}/{/if}{if $Nombre}Nombre/{$Nombre}/{/if}{if $EstadoSeleccionado}Estado/{$EstadoSeleccionado}/{/if}{if $FechaDesde}FechaDesde/{$FechaDesde}/{/if}{if $FechaHasta}FechaHasta/{$FechaHasta}/{/if}{if $EstadoId >= 0 and $EstadoId}EstadoOrdenTrabajoId/{$EstadoId}/{/if}{if $NombreProveedor}NombreProveedor/{$NombreProveedor}/{/if}{if $OrdenDeCompraId}OrdenDeCompraId/{$OrdenDeCompraId}/{/if}{if $OrdenEstadoId >= 0 and $OrdenEstadoId }EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $NombreCliente}NombreCliente/{$NombreCliente}/{/if}{if $ProveedorNombre}ProveedorNombre/{$ProveedorNombre}/{/if}{if $FacturaId}FacturaId/{$FacturaId}/{/if}{if $FacturaTipo}FacturaTipo/{$FacturaTipo}/{/if}{if $OrdenDeTrabajoId}OrdenDeTrabajoId/{$OrdenDeTrabajoId}/{/if}{if $OrdenEstadoId >= 0}EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $SelectedPrioridadId}PrioridadId/{$SelectedPrioridadId}/{/if}pagesize/{$list.pageSize}/page/{$pageNum}{if $orderBy}/order/{$orderBy}_{$order}{/if}{if $search}/search/{$search}{/if}" title="Página {$pageNum}" {if $pageNum eq $list.page}class="active"{/if}>{$pageNum}</a>
                     {/foreach}
                  </li>
                  <li>
                     <a href="/{$varController}/{$varAction}/{if $Pagado}Pagado/{$Pagado}/{/if}{if $Pendientes}Pendientes/{$Pendientes}/{/if}{if $ProveedorId}ProveedorId/{$ProveedorId}/{/if}{if $Nombre}Nombre/{$Nombre}/{/if}{if $EstadoSeleccionado}Estado/{$EstadoSeleccionado}/{/if}{if $FechaDesde}FechaDesde/{$FechaDesde}/{/if}{if $FechaHasta}FechaHasta/{$FechaHasta}/{/if}{if $EstadoId >= 0 and $EstadoId}EstadoOrdenTrabajoId/{$EstadoId}/{/if}{if $NombreProveedor}NombreProveedor/{$NombreProveedor}/{/if}{if $OrdenDeCompraId}OrdenDeCompraId/{$OrdenDeCompraId}/{/if}{if $OrdenEstadoId >= 0 and $OrdenEstadoId }EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $NombreCliente}NombreCliente/{$NombreCliente}/{/if}{if $ProveedorNombre}ProveedorNombre/{$ProveedorNombre}/{/if}{if $FacturaId}FacturaId/{$FacturaId}/{/if}{if $FacturaTipo}FacturaTipo/{$FacturaTipo}/{/if}{if $OrdenDeTrabajoId}OrdenDeTrabajoId/{$OrdenDeTrabajoId}/{/if}{if $OrdenEstadoId >= 0}EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $SelectedPrioridadId}PrioridadId/{$SelectedPrioridadId}/{/if}pagesize/{$list.pageSize}/page/{if $list.nextPage < $list.pageCount}{$list.nextPage}{else}{$list.pageCount}{/if}{if $orderBy}/order/{$orderBy}_{$order}{/if}{if $search}/search/{$search}{/if}" title="Siguiente">Siguiente</a>
                  </li>
                  <li>
                     <a href="/{$varController}/{$varAction}/{if $Pagado}Pagado/{$Pagado}/{/if}{if $Pendientes}Pendientes/{$Pendientes}/{/if}{if $ProveedorId}ProveedorId/{$ProveedorId}/{/if}{if $Nombre}Nombre/{$Nombre}/{/if}{if $EstadoSeleccionado}Estado/{$EstadoSeleccionado}/{/if}{if $FechaDesde}FechaDesde/{$FechaDesde}/{/if}{if $FechaHasta}FechaHasta/{$FechaHasta}/{/if}{if $EstadoId >= 0 and $EstadoId}EstadoOrdenTrabajoId/{$EstadoId}/{/if}{if $NombreProveedor}NombreProveedor/{$NombreProveedor}/{/if}{if $OrdenDeCompraId}OrdenDeCompraId/{$OrdenDeCompraId}/{/if}{if $OrdenEstadoId >= 0 and $OrdenEstadoId }EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $NombreCliente}NombreCliente/{$NombreCliente}/{/if}{if $ProveedorNombre}ProveedorNombre/{$ProveedorNombre}/{/if}{if $FacturaId}FacturaId/{$FacturaId}/{/if}{if $FacturaTipo}FacturaTipo/{$FacturaTipo}/{/if}{if $OrdenDeTrabajoId}OrdenDeTrabajoId/{$OrdenDeTrabajoId}/{/if}{if $OrdenEstadoId >= 0}EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $SelectedPrioridadId}PrioridadId/{$SelectedPrioridadId}/{/if}pagesize/{$list.pageSize}/page/{$list.pageCount}{if $orderBy}/order/{$orderBy}_{$order}{/if}{if $search}/search/{$search}{/if}" title="Última">Ultima &raquo;</a>
                  </li>
               </ul> <!-- /paginadorOptions -->
            
            </div> <!-- /listPaginador -->