<?php

/**
 * HistorialEfectivo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class HistorialEfectivo extends BaseHistorialEfectivo
{
	public function setUp()
	{
		parent::setUp();
	
	
		//$this->hasAccessorMutator('FechaAnulacion', 'FechaAnulacionAccessor', 'FechaAnulacionMutator');
	
		$this->hasAccessorMutator('Fecha', 'FechaAccessor', 'FechaMutator');
	}
	
	public function FechaMutator( $value )
	{
		$dateHelper =   new Classes_DateHelper();
		$date 	=	$dateHelper->fromViewFormat($value);
		 
		 
		$this->_set('Fecha', $date);
	}
	
	public function FechaAccessor()
	{
		$timestamp	=	$this->_get('Fecha');
		 
		if ($timestamp)
		{
			// convertir timestamp a dd/mm/aaaa
			$dateHelper =   new Classes_DateHelper();
			 
			$date 	=	$dateHelper->toViewFormat($timestamp);
			 
			return substr($date, 0, 10);
		}
		else
			return '';
	}
	
}