<?php

/**
 * Liquidacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Liquidacion extends BaseLiquidacion
{
	public function setUp()
    {
        parent::setUp();
        
        
        $this->hasAccessorMutator('FechaFactura', 'FechaAccessor', 'FechaMutator');
    }
    
    
    
    public function FechaMutator( $value )
    {
        $dateHelper =   new Classes_DateHelper();
    	$date 	=	$dateHelper->fromViewFormat($value);
    	
    	
        $this->_set('FechaFactura', $date);
    }
    
    public function FechaAccessor()
    {
    	$timestamp	=	$this->_get('FechaFactura');
    	
    	if ($timestamp)
    	{
    		// convertir timestamp a dd/mm/aaaa
		    $dateHelper =   new Classes_DateHelper();
    	
        	$date 	=	$dateHelper->toViewFormat($timestamp);
        	
        	return $date;
    	}
    	else
    		return '';
    }
	
}