<?php

/**
 * NotaCredito
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class NotaCredito extends BaseNotaCredito
{
	public function setUp()
	{
		parent::setUp();
	
		$this->hasAccessorMutator('Fecha', 'FechaAccessor', 'FechaMutator');
	
	}
	
	public function FechaMutator( $value )
	{
		$date 	=	new Classes_DateHelper();
	
		$this->_set('Fecha', $date->fromViewFormat($value));
	}
	
	public function FechaAccessor()
	{
		$timestamp	=	$this->_get('Fecha');
		 
		if ($timestamp)
		{
			$date 	=	new Classes_DateHelper();
			 
			return $date->toViewFormat($timestamp);
		}
		else
			return '';
	}
	
	
	public function Create($data)
	{
		if(isset($data))
		{
			$c	=	new NotaCredito();
	
			if(isset($data['ClienteId']) and is_numeric($data['ClienteId']))
			{
				$clienteId	=	$data['ClienteId'];
				$cliente	=	Doctrine::getTable('Cliente')->FindOneById($clienteId);
	
				if(is_object($cliente))
				{
					// obtener ultimo numero de factura o credito
					$facturacion	=	new Classes_FacturaFactory($cliente, $data['Fecha'], array(1,2));
					
					$tipoIva	=	Doctrine::getTable('TipoIva')->FindOneById($data['TipoIvaId']);
					if(!is_object($tipoIva))
						throw new Exception('No se ha encontrado el tipo de iva seleccionado');
					
					$ultimoNumero	=	$facturacion->GetUltimoNumeroFactura($tipoIva->GetLetraFactura());
					
					$c->Numero	=	$ultimoNumero + 1;
						
					$c->Fecha	=	$data['Fecha'];
					$c->ClienteId	=	$data['ClienteId'];
					$c->TipoIvaId	=	$data['TipoIvaId'];
					$c->Importe	=	$data['Importe'];
					$c->Descripcion	=	$data['Descripcion'];
	
					$c->save();
	
					return $c;
				}
				else
					echo 'Error: el objeto cliente no fue encontrado';
	
			}
		}
	}
	
}