<?php

/**
 * OrdenDePagoFacturaCompra
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class OrdenDePagoFacturaCompra extends BaseOrdenDePagoFacturaCompra
{
	// agregar control en post insert para 
	// 		controlar si la suma total liquidada en ordenes de pago es mayor o igual 
	//			al importe de la factura, marcarla como pagada
	public function postInsert( $event)
	{
		$invoker = $event->getInvoker();
	
		$this->ControlarPagoDeFactura();
	}

	public function ControlarPagoDeFactura()
	{
		// si pago total de factura es mayor o igual al importe de la factura, 
		// marca como pagada
		
		$f	=	$this->GetFacturaCompra();
		// una factura de compra puede pagarse como anticipos de ordenes de compra
		// o con pagos parciales
		if(!$f->IsPendienteDePago())
		{
			$f->PendienteDePago = 'NO';
			$f->save();
		}
	}
	
	public function GetFacturaCompra()
	{
		$filters	=	array();
		$filters['Numero']	=	$this->FacturaNumero;
		$filters['TipoIvaId']	=	$this->TipoIvaId;
		$filters['ProveedorId']	=	$this->ProveedorId;
		
		$coleccion	= Doctrine::getTable('FacturaCompra')->GetByFilter($filters)->execute();
		foreach ($coleccion as $f)
		{
			return $f;
		}
		
		throw new Exception('No fue posible obtener la factura');
	}
}