<?php

/**
 * Presupuesto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Presupuesto extends BasePresupuesto
{
    public function setUp()
    {
        parent::setUp();
        

        $this->hasAccessorMutator('Fecha', 'FechaAccessor', 'FechaMutator');
        $this->hasAccessor('Comentario', 'ComentarioAccessor');
    
    }
    

	public function ComentarioAccessor()
    {
    	return	nl2br($this->_get('Comentario'));
    	
    }
    
    public function FechaMutator( $value )
    {
        $date 	=	new Classes_DateHelper();
        
        $this->_set('Fecha', $date->fromViewFormat($value));
    }
    
    public function FechaAccessor()
    {
    	$timestamp	=	$this->_get('Fecha');
    	
    	if ($timestamp)
    	{
        	$date 	=	new Classes_DateHelper();
        	
        	return $date->toViewFormat($timestamp);
    	}
    	else
    		return '';
    }
    
    public function GetResumen($orden = null)
    {
    	$a	=	array();
    	
    	if(!is_object($orden))
    		$orden	=	$this->GetOneOrdenDeTrabajo();
    	
    	
	    	$a['OrdenId']	=	$orden->Id;
	    	$a['Cliente']	=	$orden->Cliente;
	    	$a['Producto']	=	$orden->Producto;
	    	$a['Orden']	=	$orden;
	    	$a['Caracteristicas']	=	$orden->DescripcionDeTrabajo;
	    	$a['CostosSinIVa']	=	number_format($orden->GetCosto(),2,'.','');
	    	$a['Presupuesto']	=	$this;
    	
    	
    	return $a;
   
    }
    
    public function Aprobar()
    {
    	$orden	=	$this->GetOneOrdenDeTrabajo();
    	$mng	=	new Classes_EstadosManager($orden);
    	$mng->SetEstadoAprobado();
    	$this->FechaAprobacion	=	date('Y-m-d');
    	$this->save();
    	
    	$orden = $this->GetOneOrdenDeTrabajo();
    	$orden->SetFechaFinalizacion();
    	$orden->SetFechaProximoCambioDeEstado(); //usado en preproduccion
    }
    
    public function GetOneOrdenDeTrabajo()
    {
    	foreach($this->OrdenDeTrabajo as $a)
    	{
    		return $a;
    	}
    }
    
	
}