<?php

/**
 * TipoIva
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class TipoIva extends BaseTipoIva
{
	public function GetLetraFactura()
	{
		return $this->Letra_comp;
	}
	
	public function GetPorcentajeIva()
	{
		
		    switch ($this->GetLetraFactura())
        	{
        		case 'A': {return $this->Discriminado; break;}
        		case 'B': {return $this->Incluido; break;}
        		case 'N': {return $this->Incluido; break;}
        		default: {return $this->Incluido; break;}
        	}
		
	}
}