            <div class="listTop">
                <div>
                    <table border="0" cellpadding="0" cellspacing="0">
                        <tr>
                            
                            
                            <td width="5%"><p href="/{$varController}/{$varAction}/{if $OrdenEstadoId >= 0}EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $NombreCliente}NombreCliente/{$NombreCliente}/{/if}{if $OrdenDeTrabajoId}OrdenDeTrabajoId/{$OrdenDeTrabajoId}/{/if}{if $SelectedPrioridadId}PrioridadId/{$SelectedPrioridadId}/{/if}pagesize/{$list.pageSize}/page/{$list.page}/order/Id_{if $order eq 'DESC'}ASC{else}DESC{/if}{if $search}/search/{$search}{/if}" class="{if $orderBy eq 'Id'}{if $order eq 'ASC'}orderUp{else}orderDown{/if}{else}orderNone{/if}" title="Numero">Numero</p></td>
                            
                            <td width="10%"><p href="/{$varController}/{$varAction}/{if $OrdenEstadoId >= 0}EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $NombreCliente}NombreCliente/{$NombreCliente}/{/if}{if $OrdenDeTrabajoId}OrdenDeTrabajoId/{$OrdenDeTrabajoId}/{/if}{if $SelectedPrioridadId}PrioridadId/{$SelectedPrioridadId}/{/if}pagesize/{$list.pageSize}/page/{$list.page}/order/Producto_{if $order eq 'DESC'}ASC{else}DESC{/if}{if $search}/search/{$search}{/if}" class="{if $orderBy eq 'Producto'}{if $order eq 'ASC'}orderUp{else}orderDown{/if}{else}orderNone{/if}" title="Producto">Producto</p></td>
                            <td width="10%"><p href="/{$varController}/{$varAction}/{if $OrdenEstadoId >= 0}EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $NombreCliente}NombreCliente/{$NombreCliente}/{/if}{if $OrdenDeTrabajoId}OrdenDeTrabajoId/{$OrdenDeTrabajoId}/{/if}{if $SelectedPrioridadId}PrioridadId/{$SelectedPrioridadId}/{/if}pagesize/{$list.pageSize}/page/{$list.page}/order/OrdenDeTrabajo.Cliente.Nombre_{if $order eq 'DESC'}ASC{else}DESC{/if}{if $search}/search/{$search}{/if}" class="{if $orderBy eq 'OrdenDeTrabajo.Cliente.Nombre'}{if $order eq 'ASC'}orderUp{else}orderDown{/if}{else}orderNone{/if}" title="Nombre cliente">Nombre cliente</p></td>
                            <td width="10%"><p href="/{$varController}/{$varAction}/{if $OrdenEstadoId >= 0}EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $NombreCliente}NombreCliente/{$NombreCliente}/{/if}{if $OrdenDeTrabajoId}OrdenDeTrabajoId/{$OrdenDeTrabajoId}/{/if}{if $SelectedPrioridadId}PrioridadId/{$SelectedPrioridadId}/{/if}pagesize/{$list.pageSize}/page/{$list.page}/order/OrdenDeTrabajo.Estado.Nombre_{if $order eq 'DESC'}ASC{else}DESC{/if}{if $search}/search/{$search}{/if}" class="{if $orderBy eq 'OrdenDeTrabajo.Estado.Nombre'}{if $order eq 'ASC'}orderUp{else}orderDown{/if}{else}orderNone{/if}" title="Estado">Estado</p></td>
                            
                            <td width="10%"><p href="/{$varController}/{$varAction}/{if $OrdenEstadoId >= 0}EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $NombreCliente}NombreCliente/{$NombreCliente}/{/if}{if $OrdenDeTrabajoId}OrdenDeTrabajoId/{$OrdenDeTrabajoId}/{/if}{if $SelectedPrioridadId}PrioridadId/{$SelectedPrioridadId}/{/if}pagesize/{$list.pageSize}/page/{$list.page}/order/DescripcionDeTrabajo_{if $order eq 'DESC'}ASC{else}DESC{/if}{if $search}/search/{$search}{/if}" class="{if $orderBy eq 'DescripcionDeTrabajo'}{if $order eq 'ASC'}orderUp{else}orderDown{/if}{else}orderNone{/if}" title="Costo total de insumos elegidos al momento de pasar a Produccion">Costo congelado</p></td>
                            <td width="10%"><p href="/{$varController}/{$varAction}/{if $OrdenEstadoId >= 0}EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $NombreCliente}NombreCliente/{$NombreCliente}/{/if}{if $OrdenDeTrabajoId}OrdenDeTrabajoId/{$OrdenDeTrabajoId}/{/if}{if $SelectedPrioridadId}PrioridadId/{$SelectedPrioridadId}/{/if}pagesize/{$list.pageSize}/page/{$list.page}/order/DescripcionDeTrabajo_{if $order eq 'DESC'}ASC{else}DESC{/if}{if $search}/search/{$search}{/if}" class="{if $orderBy eq 'DescripcionDeTrabajo'}{if $order eq 'ASC'}orderUp{else}orderDown{/if}{else}orderNone{/if}" title="Costo total de insumos elegidos que tienen orden de compra (si una OC es anulada, el insumo pasa a estar no elegido)">Costo total</p></td>
                            <td width="10%"><p href="/{$varController}/{$varAction}/{if $OrdenEstadoId >= 0}EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $NombreCliente}NombreCliente/{$NombreCliente}/{/if}{if $OrdenDeTrabajoId}OrdenDeTrabajoId/{$OrdenDeTrabajoId}/{/if}{if $SelectedPrioridadId}PrioridadId/{$SelectedPrioridadId}/{/if}pagesize/{$list.pageSize}/page/{$list.page}/order/DescripcionDeTrabajo_{if $order eq 'DESC'}ASC{else}DESC{/if}{if $search}/search/{$search}{/if}" class="{if $orderBy eq 'DescripcionDeTrabajo'}{if $order eq 'ASC'}orderUp{else}orderDown{/if}{else}orderNone{/if}" title="Diferencia entre costo total y costo congelado">Diferencia</p></td>
                            <td width="10%"><p href="/{$varController}/{$varAction}/{if $OrdenEstadoId >= 0}EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $NombreCliente}NombreCliente/{$NombreCliente}/{/if}{if $OrdenDeTrabajoId}OrdenDeTrabajoId/{$OrdenDeTrabajoId}/{/if}{if $SelectedPrioridadId}PrioridadId/{$SelectedPrioridadId}/{/if}pagesize/{$list.pageSize}/page/{$list.page}/order/DescripcionDeTrabajo_{if $order eq 'DESC'}ASC{else}DESC{/if}{if $search}/search/{$search}{/if}" class="{if $orderBy eq 'DescripcionDeTrabajo'}{if $order eq 'ASC'}orderUp{else}orderDown{/if}{else}orderNone{/if}" title="Precio de venta sin IVA de la orden">Precio venta</p></td>
                            <td width="10%"><p href="/{$varController}/{$varAction}/{if $OrdenEstadoId >= 0}EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $NombreCliente}NombreCliente/{$NombreCliente}/{/if}{if $OrdenDeTrabajoId}OrdenDeTrabajoId/{$OrdenDeTrabajoId}/{/if}{if $SelectedPrioridadId}PrioridadId/{$SelectedPrioridadId}/{/if}pagesize/{$list.pageSize}/page/{$list.page}/order/DescripcionDeTrabajo_{if $order eq 'DESC'}ASC{else}DESC{/if}{if $search}/search/{$search}{/if}" class="{if $orderBy eq 'DescripcionDeTrabajo'}{if $order eq 'ASC'}orderUp{else}orderDown{/if}{else}orderNone{/if}" title="Ganancia de la orden: precio de venta menos la sumatoria de insumos elegidos">Ganancia</p></td>
                            <td width="10%"><p href="/{$varController}/{$varAction}/{if $OrdenEstadoId >= 0}EstadoOrdenTrabajoId/{$OrdenEstadoId}/{/if}{if $NombreCliente}NombreCliente/{$NombreCliente}/{/if}{if $OrdenDeTrabajoId}OrdenDeTrabajoId/{$OrdenDeTrabajoId}/{/if}{if $SelectedPrioridadId}PrioridadId/{$SelectedPrioridadId}/{/if}pagesize/{$list.pageSize}/page/{$list.page}/order/DescripcionDeTrabajo_{if $order eq 'DESC'}ASC{else}DESC{/if}{if $search}/search/{$search}{/if}" class="{if $orderBy eq 'DescripcionDeTrabajo'}{if $order eq 'ASC'}orderUp{else}orderDown{/if}{else}orderNone{/if}" title="Numero de factura">Factura</p></td>
                              
                            
                            <td width="6%"><p>Opciones</p></td>
                        </tr>
                    </table>
                </div>
            </div> <!-- /listadoTop -->