            <div class="listTop">
                <div>
                    <table border="0" cellpadding="0" cellspacing="0">
                        <tr>
                            
                            
                            <td width="10%"><a href="/{$varController}/{$varAction}/{if $FechaDesde}FechaDesde/{$FechaDesde}/{/if}{if $FechaHasta}FechaHasta/{$FechaHasta}/{/if}{if $Pagado}Pagado/{$Pagado}/{/if}{if $NombreProveedor}NombreProveedor/{$NombreProveedor}/{/if}{if $OrdenDeCompraId}OrdenDeCompraId/{$OrdenDeCompraId}/{/if}{if $Pendientes}Pendientes/{$Pendientes}/{/if}{if $OrdenDePagoId}OrdenDePagoId/{$OrdenDePagoId}/{/if}pagesize/{$list.pageSize}/page/{$list.page}/order/Fecha_{if $order eq 'DESC'}ASC{else}DESC{/if}{if $search}/search/{$search}{/if}" class="{if $orderBy eq 'Fecha'}{if $order eq 'ASC'}orderUp{else}orderDown{/if}{else}orderNone{/if}" title="Fecha">Fecha</a></td>
                            <td width="10%"><a href="/{$varController}/{$varAction}/{if $FechaDesde}FechaDesde/{$FechaDesde}/{/if}{if $FechaHasta}FechaHasta/{$FechaHasta}/{/if}{if $Pagado}Pagado/{$Pagado}/{/if}{if $NombreProveedor}NombreProveedor/{$NombreProveedor}/{/if}{if $OrdenDeCompraId}OrdenDeCompraId/{$OrdenDeCompraId}/{/if}{if $Pendientes}Pendientes/{$Pendientes}/{/if}{if $OrdenDePagoId}OrdenDePagoId/{$OrdenDePagoId}/{/if}pagesize/{$list.pageSize}/page/{$list.page}/order/Id_{if $order eq 'DESC'}ASC{else}DESC{/if}{if $search}/search/{$search}{/if}" class="{if $orderBy eq 'Id'}{if $order eq 'ASC'}orderUp{else}orderDown{/if}{else}orderNone{/if}" title="Numero de orden de compra">OC</a></td>
                            <td width="10%"><p href="/{$varController}/{$varAction}/{if $FechaDesde}FechaDesde/{$FechaDesde}/{/if}{if $FechaHasta}FechaHasta/{$FechaHasta}/{/if}{if $Pagado}Pagado/{$Pagado}/{/if}{if $NombreProveedor}NombreProveedor/{$NombreProveedor}/{/if}{if $OrdenDeCompraId}OrdenDeCompraId/{$OrdenDeCompraId}/{/if}{if $Pendientes}Pendientes/{$Pendientes}/{/if}{if $OrdenDePagoId}OrdenDePagoId/{$OrdenDePagoId}/{/if}pagesize/{$list.pageSize}/page/{$list.page}/order/Id_{if $order eq 'DESC'}ASC{else}DESC{/if}{if $search}/search/{$search}{/if}" class="{if $orderBy eq 'Id'}{if $order eq 'ASC'}orderUp{else}orderDown{/if}{else}orderNone{/if}" title="Orden de trabajo">OT</p></td>
                            
                            <td width="20%"><p href="/{$varController}/{$varAction}/{if $FechaDesde}FechaDesde/{$FechaDesde}/{/if}{if $FechaHasta}FechaHasta/{$FechaHasta}/{/if}{if $Pagado}Pagado/{$Pagado}/{/if}{if $NombreProveedor}NombreProveedor/{$NombreProveedor}/{/if}{if $OrdenDeCompraId}OrdenDeCompraId/{$OrdenDeCompraId}/{/if}{if $Pendientes}Pendientes/{$Pendientes}/{/if}{if $OrdenDePagoId}OrdenDePagoId/{$OrdenDePagoId}/{/if}pagesize/{$list.pageSize}/page/{$list.page}/order/Id_{if $order eq 'DESC'}ASC{else}DESC{/if}{if $search}/search/{$search}{/if}" class="{if $orderBy eq 'Id'}{if $order eq 'ASC'}orderUp{else}orderDown{/if}{else}orderNone{/if}" title="Proveedor">Proveedor</p></td>
                            
                            <td width="10%"><p href="/{$varController}/{$varAction}/{if $FechaDesde}FechaDesde/{$FechaDesde}/{/if}{if $FechaHasta}FechaHasta/{$FechaHasta}/{/if}{if $Pagado}Pagado/{$Pagado}/{/if}{if $NombreProveedor}NombreProveedor/{$NombreProveedor}/{/if}{if $OrdenDeCompraId}OrdenDeCompraId/{$OrdenDeCompraId}/{/if}{if $Pendientes}Pendientes/{$Pendientes}/{/if}{if $OrdenDePagoId}OrdenDePagoId/{$OrdenDePagoId}/{/if}pagesize/{$list.pageSize}/page/{$list.page}/order/Id_{if $order eq 'DESC'}ASC{else}DESC{/if}{if $search}/search/{$search}{/if}" class="{if $orderBy eq 'Id'}{if $order eq 'ASC'}orderUp{else}orderDown{/if}{else}orderNone{/if}" title="Numero de orden de compra">Total</p></td>
                            <td width="10%"><p href="/{$varController}/{$varAction}/{if $FechaDesde}FechaDesde/{$FechaDesde}/{/if}{if $FechaHasta}FechaHasta/{$FechaHasta}/{/if}{if $Pagado}Pagado/{$Pagado}/{/if}{if $NombreProveedor}NombreProveedor/{$NombreProveedor}/{/if}{if $OrdenDeCompraId}OrdenDeCompraId/{$OrdenDeCompraId}/{/if}{if $Pendientes}Pendientes/{$Pendientes}/{/if}{if $OrdenDePagoId}OrdenDePagoId/{$OrdenDePagoId}/{/if}pagesize/{$list.pageSize}/page/{$list.page}/order/Id_{if $order eq 'DESC'}ASC{else}DESC{/if}{if $search}/search/{$search}{/if}" class="{if $orderBy eq 'Id'}{if $order eq 'ASC'}orderUp{else}orderDown{/if}{else}orderNone{/if}" title="Total validado en facturas de compra">Total validado</p></td>
                            
                            <td width="10%"><p href="/{$varController}/{$varAction}/{if $FechaDesde}FechaDesde/{$FechaDesde}/{/if}{if $FechaHasta}FechaHasta/{$FechaHasta}/{/if}{if $Pagado}Pagado/{$Pagado}/{/if}{if $NombreProveedor}NombreProveedor/{$NombreProveedor}/{/if}{if $OrdenDeCompraId}OrdenDeCompraId/{$OrdenDeCompraId}/{/if}{if $Pendientes}Pendientes/{$Pendientes}/{/if}{if $OrdenDePagoId}OrdenDePagoId/{$OrdenDePagoId}/{/if}pagesize/{$list.pageSize}/page/{$list.page}/order/FechaAnulacion_{if $order eq 'DESC'}ASC{else}DESC{/if}{if $search}/search/{$search}{/if}" class="{if $orderBy eq 'FechaAnulacion'}{if $order eq 'ASC'}orderUp{else}orderDown{/if}{else}orderNone{/if}" title="Indica si una orden esta vigente o fue anulada">Estado</p></td>
                            <td width="10%"><a href="/{$varController}/{$varAction}/{if $FechaDesde}FechaDesde/{$FechaDesde}/{/if}{if $FechaHasta}FechaHasta/{$FechaHasta}/{/if}{if $Pagado}Pagado/{$Pagado}/{/if}{if $NombreProveedor}NombreProveedor/{$NombreProveedor}/{/if}{if $OrdenDeCompraId}OrdenDeCompraId/{$OrdenDeCompraId}/{/if}{if $Pendientes}Pendientes/{$Pendientes}/{/if}{if $OrdenDePagoId}OrdenDePagoId/{$OrdenDePagoId}/{/if}pagesize/{$list.pageSize}/page/{$list.page}/order/OrdenDePagoId_{if $order eq 'DESC'}ASC{else}DESC{/if}{if $search}/search/{$search}{/if}" class="{if $orderBy eq 'OrdenDePagoId'}{if $order eq 'ASC'}orderUp{else}orderDown{/if}{else}orderNone{/if}" title="Orden de pago">Orden de pago</a></td>
                            
                            
                              
                            
                            <td width="10%"><p>Opciones</p></td>
                        </tr>
                    </table>
                </div>
            </div> <!-- /listadoTop -->